### ISSUE TITLE
Unable to List Collections.

### ISSUE THREAD

**Issue by jimthree** [adammartin/azure-documentdb-rubysdk#2]
Thanks very much for your work on the DocumentDB SDK for Ruby!

I don't seem to be able to list collections, I may be doing something really stupid, but also, MS may have changed something that has broken the SDK.

my sample code looks like this:

```
require 'documentdb'

url_endpoint = "https://xxxx.documents.azure.com:443/"
master_key = "xxxx"

context = Azure::DocumentDB::Context.new url_endpoint, master_key
database = Azure::DocumentDB::Database.new context, RestClient

db_instance_id = database.list["Databases"][0]["_rid"]
collection = database.collection_for_rid db_instance_id
puts collection.list
```

when I call collection.list, RestClient returns a 400

```
jim:documentDB jimb$ ruby docdb.rb
/Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 400 Bad Request (RestClient::BadRequest)
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    from /Users/jimb/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:853:in `start'
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
    from /Users/jimb/.rvm/gems/ruby-2.3.0@docdb/gems/azure-documentdb-sdk-0.2.1/lib/collection/collection.rb:22:in `list'
    from docdb.rb:11:in `<main>'
```

Is this expected, what would I be doing wrong? If I call collection.URI it returns fine.
The DocumentDB has one Database, with one collection, with one document in it.

**Comment by knegg** [comment]
Hi there, 

did you ever find out of this - get the same error when trying.

**Edit:**
Found a solution to this problem. At least this worked for me.
in lib/version/version.rb set:
`SERVICE_VERSION = '2017-02-22'.freeze`

I used RVM and had to add correct version in the `/lib/version/version.rb` within the `~/.rvm/gems/ruby-2.3.7/gems/azure-documentdb-sdk-0.1.1/lib/version/version.rb`.

List of all Supported REST API Versions of MS Azure Cosmos DB:
[https://docs.microsoft.com/nb-no/rest/api/cosmos-db/#supported-rest-api-versions](https://docs.microsoft.com/nb-no/rest/api/cosmos-db/#supported-rest-api-versions)

I used [HTTP Toolkit](https://httptoolkit.tech/view/ruby/) to debug request header. Within the response body, there was a clue:
`The collection 'your-named-collection' could not be read because it was created with a newer API version.`

Using this tool you can also check that the `x-ms-version` in the GET header is set to a valid date (one from the list above).

Hope this helps and saves others some hours of debugging.
